# documentation: https://www.classicpress.net/
# slogan: A lightweight, stable, instantly familiar free open-source content management system, based on WordPress without the block editor (Gutenberg).
# category: cms
# tags: cms, blog, content, management
# logo: svgs/classicpress.svg

services:
   classicpress:
    image: classicpress/classicpress:latest
    volumes:
       - classicpress-files:/var/www/html
    environment:
       - SERVICE_URL_CLASSICPRESS
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1"]
      interval: 2s
      timeout: 10s
      retries: 10
