# documentation: https://dozzle.dev/guide/getting-started#running-with-docker
# slogan: Dozzle is a simple and lightweight web UI for Docker logs.
# category: devtools
# tags: dozzle,docker,logs,web-ui
# logo: svgs/dozzle.svg
# port: 8080

services:
  dozzle:
    image: amir20/dozzle:latest
    environment:
      - SERVICE_URL_DOZZLE_8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
