# documentation: https://github.com/aldinokemal/go-whatsapp-web-multidevice
# slogan: Golang WhatsApp - Built with Go for efficient memory use
# category: cms
# tags: whatsapp,golang,multidevice,api,go-whatsapp
# logo: svgs/gowa.svg
# port: 3000

services:
  gowa:
    image: aldinokemal2104/go-whatsapp-web-multidevice:latest
    environment:
      - SERVICE_URL_GOWA_3000
      - SERVICE_USER_GOWA
      - SERVICE_PASSWORD_GOWA
      - APP_BASIC_AUTH=${SERVICE_USER_GOWA}:${SERVICE_PASSWORD_GOWA}
      - APP_PORT=3000
      - APP_DEBUG=${APP_DEBUG:-false}
      - APP_ACCOUNT_VALIDATION=${APP_ACCOUNT_VALIDATION:-false}
      - WHATSAPP_WEBHOOK=${WHATSAPP_WEBHOOK}
      - WHATSAPP_WEBHOOK_SECRET=${WHATSAPP_WEBHOOK_SECRET}
    volumes:
      - gowa_data:/app/storages
