# documentation: https://github.com/grocy/grocy
# slogan: Grocy is a web-based household management and grocery list application.
# category: productivity
# tags: groceries, household, management, grocery, shopping
# logo: svgs/grocy.svg

services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    environment:
      - SERVICE_URL_GROCY
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - grocy-config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 2s
      timeout: 10s
      retries: 15
