# documentation: https://www.meilisearch.com
# slogan: MeiliSearch is a powerful, fast, easy to use and deploy search engine.
# category: search
# tags: search,engine,fulltext,full,text,meilisearch
# logo: svgs/meilisearch.svg
# port: 7700

services:
  meilisearch:
    image: getmeili/meilisearch:latest
    environment:
      - SERVICE_URL_MEILISEARCH_7700
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-production}
      - MEILI_MASTER_KEY=${SERVICE_PASSWORD_MEILISEARCH}
    volumes:
      - meilisearch-data:/meili_data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:7700/health"]
      interval: 2s
      timeout: 10s
      retries: 15
