# documentation: https://github.com/alexta69/metube
# slogan: A web GUI for youtube-dl with playlist support. It enables you to effortlessly download videos from YouTube and dozens of other sites.
# category: media
# tags: youtube, download, videos, playlist
# port: 8081

services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    environment:
      - SERVICE_URL_METUBE_8081
      - UID=1000
      - GID=1000
    volumes:
      - metube-downloads:/downloads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8081"]
      interval: 2s
      timeout: 10s
      retries: 15
