# documentation: https://moodle.org
# slogan: Moodle is the world’s most customisable and trusted eLearning solution that empowers educators to improve our world.
# category: cms
# tags: moodle, elearning, education, lms, cms, open, source, low, code
# logo: svgs/moodle.png
# port: 8080

services:
  mariadb:
    image: mariadb:11.1
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_PASSWORD=$SERVICE_PASSWORD_ROOT
      - MYSQL_DATABASE=bitnami_moodle
      - MYSQL_USER=$SERVICE_USER_MARIADB
      - MYSQL_PASSWORD=$SERVICE_PASSWORD_MARIADB
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb-data:/var/lib/mysql

  moodle:
    image: docker.io/bitnami/moodle:4.3
    environment:
      - SERVICE_URL_MOODLE_8080
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=$SERVICE_USER_MARIADB
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=$SERVICE_PASSWORD_MARIADB
      - ALLOW_EMPTY_PASSWORD=no
      - MOODLE_USERNAME=${MOODLE_USERNAME:-user}
      - MOODLE_PASSWORD=$SERVICE_PASSWORD_MOODLE
      - MOODLE_EMAIL=user@example.com
      - MOODLE_SITE_NAME=${MOODLE_SITE_NAME:-New Site}
    volumes:
      - moodle-data:/bitnami/moodle
      - moodledata-data:/bitnami/moodledata
    depends_on:
      - mariadb
