# documentation: https://github.com/PrivateBin/PrivateBin/blob/master/doc/README.md
# slogan: PrivateBin is a minimalist, open source online pastebin where the server has zero knowledge of pasted data.
# category: security
# tags: text, sharing
# logo: svgs/privatebin.svg
# port: 8080

services:
  privatebin:
    image: privatebin/nginx-fpm-alpine
    environment:
      - SERVICE_URL_PRIVATEBIN_8080
    volumes:
      - privatebin_data:/srv/data
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/"]
      interval: 5s
      timeout: 20s
      retries: 10
