# documentation: https://hub.docker.com/r/linuxserver/prowlarr
# slogan: Prowlarr⁠ is a indexer manager/proxy built on the popular arr .net/reactjs base stack to integrate with your various PVR apps.
# category: media
# tags: media, server, movies, tv, indexer, torrent, nzb, usenet
# logo: svgs/prowlarr.svg
# port: 9696

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - SERVICE_URL_PROWLARR_9696
      - _APP_URL=$SERVICE_URL_PROWLARR
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Toronto}
    volumes:
      - prowlarr-config:/config
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696/ping"]
      interval: 2s
      timeout: 10s
      retries: 15
