# documentation: https://syncthing.net/
# slogan: Syncthing synchronizes files between two or more computers in real time.
# category: storage
# tags: filestorage, data, synchronization
# logo: svgs/syncthing.svg
# port: 8384

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    environment:
      - SERVICE_URL_SYNCTHING_8384
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - syncthing_config:/config
      - syncthing_data1:/data1
      - syncthing_data2:/data2
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8384/"]
      interval: 5s
      timeout: 20s
      retries: 10
